const INITIAL_STATE = {
  sections: [
    {
      title: "jordan",
      box_condition: "good_condition",
      brand_name: "Air Jordan",
      linkUrl: "shop/jordan",
      category: ["basketball"],
      collection_slugs: [
        "air-jordan-1",
        "goat-clean",
        "jordan",
        "jordan-1",
        "rose-bowl-flea-market",
        "the-ones-that-started-it-all",
      ],
      color: "Black",
      designer: "Peter Moore",
      details: "Black/White-Medium Grey",
      gender: ["men"],
      imageUrl:
        "https://image.goat.com/375/attachments/product_template_pictures/images/011/119/994/original/218099_00.png.png",
      has_picture: true,
      has_stock: true,
      id: 1,
      keywords: [],
      main_picture_url:
        "https://image.goat.com/750/attachments/product_template_pictures/images/011/119/994/original/218099_00.png.png",
      midsole: "Air",
      name: "Air Jordan 1 High OG 'Shadow' 2018",
      nickname: "Shadow",
      original_picture_url:
        "https://image.goat.com/attachments/product_template_pictures/images/011/119/994/original/218099_00.png.png",
      product_template_id: 218099,
      release_date: "2018-04-14T23:59:59.000Z",
      release_date_unix: 1523750399,
      release_year: 2018,
      retail_price_cents: 16000,
      shoe_condition: "used",
      silhouette: "Air Jordan 1",
      size_range: [
        10,
        10.5,
        11,
        11.5,
        12,
        12.5,
        13,
        13.5,
        14,
        14.5,
        15,
        15.5,
        16,
        16.5,
        17,
        17.5,
        18,
        3.5,
        4,
        4.5,
        5,
        5.5,
        6,
        6.5,
        7,
        7.5,
        8,
        8.5,
        9,
        9.5,
      ],
      sku: "555088 013",
      slug: "air-jordan-1-retro-high-og-shadow-2018-555088-013",
      status: "active",
      story_html:
        "<p>This Nike Air Jordan 1 Retro High OG &#39;Shadow&#39; 2018 is a retro re-release of an original 1985 colorway. The shoe features a black and medium grey leather upper with a white midsole and black outsole. It also features OG Nike Air branding on the tongue and the Wings logo on the ankle collar. It was last retroed in 2013, and a low-top version dropped in 2015.</p>\n",
      upper_material: "Leather",
    },
    {
      title: "luxurius",
      box_condition: "good_condition",
      brand_name: "Champion",
      linkUrl: "shop/luxurius",
      category: ["lifestyle"],
      collection_slugs: [],
      color: "Black",
      designer: "",
      details: "Black/White/Red",
      gender: ["men"],
      grid_picture_url:
        "https://image.goat.com/375/attachments/product_template_pictures/images/015/567/335/original/CM100018M.png.png",
      has_picture: true,
      has_stock: true,
      id: 2,
      keywords: [],
      main_picture_url:
        "https://image.goat.com/750/attachments/product_template_pictures/images/015/567/335/original/CM100018M.png.png",
      midsole: "",
      name: "Rally Pro 'Black'",
      nickname: "Black",
      original_picture_url:
        "https://image.goat.com/attachments/product_template_pictures/images/015/567/335/original/CM100018M.png.png",
      product_template_id: 468155,
      release_date: null,
      release_date_unix: null,
      release_year: null,
      retail_price_cents: 10000,
      shoe_condition: "new_no_defects",
      silhouette: "Rally Pro",
      size_range: [
        10,
        10.5,
        11,
        11.5,
        12,
        12.5,
        13,
        13.5,
        14,
        14.5,
        15,
        15.5,
        16,
        16.5,
        17,
        17.5,
        18,
        3,
        3.5,
        4,
        4.5,
        5,
        5.5,
        6,
        6.5,
        7,
        7.5,
        8,
        8.5,
        9,
        9.5,
      ],
      sku: "CM100018M",
      slug: "rally-pro-black-cm100018m",
      status: "active",
      story_html:
        "<p>The Champion Rally Pro sneaker packages street style in a sleek, basketball-inspired silhouette with heritage Champion detailing throughout. This ‘Black’ version is styled for growing kids’ feet and features a one-piece bootie construction made from woven mesh and elastic textile with suede trim on the sidewall and heel. It offers a snug, sock-like fit that’s reinforced with tabs at the tongue and heel for easy on and off. A textured chenille ‘C’ logo on the sidewall and branded elastic strap across the forefoot complement the design.</p>\n",
      upper_material: "",
    },
    {
      title: "nike",
      box_condition: "good_condition",
      brand_name: "Nike",
      linkUrl: "shop/nike",
      category: ["basketball"],
      collection_slugs: ["just-dropped", "just-dropped-1"],
      color: "Black",
      designer: "Benjamin Nethongkome",
      details: "Black/White-Bright Crimson",
      gender: ["men"],
      grid_picture_url:
        "https://image.goat.com/375/attachments/product_template_pictures/images/020/840/270/original/491192_00.png.png",
      has_picture: true,
      has_stock: true,
      id: 3,
      keywords: [],
      main_picture_url:
        "https://image.goat.com/750/attachments/product_template_pictures/images/020/840/270/original/491192_00.png.png",
      midsole: "Air",
      name: "Kyrie 5 'Friends'",
      nickname: "Friends",
      original_picture_url:
        "https://image.goat.com/attachments/product_template_pictures/images/020/840/270/original/491192_00.png.png",
      product_template_id: 491192,
      release_date: "2019-05-16T07:00:00.000Z",
      release_date_unix: 1557990000,
      release_year: 2019,
      retail_price_cents: 13000,
      shoe_condition: "new_no_defects",
      silhouette: "Kyrie 5",
      size_range: [
        10,
        10.5,
        11,
        11.5,
        12,
        12.5,
        13,
        13.5,
        14,
        14.5,
        15,
        15.5,
        16,
        16.5,
        17,
        17.5,
        18,
        3.5,
        4,
        4.5,
        5,
        5.5,
        6,
        6.5,
        7,
        7.5,
        8,
        8.5,
        9,
        9.5,
      ],
      sku: "AO2918 006",
      slug: "friends-x-kyrie-5-ao2918-006",
      status: "active",
      story_html: null,
      upper_material: null,
    },
    {
      title: "adidas",
      box_condition: "good_condition",
      brand_name: "Vans",
      linkUrl: "shop/adidas",
      category: ["skateboarding"],
      collection_slugs: [
        "quarterly-sneaker-trends",
        "rose-bowl-flea-market",
        "vans",
        "vans-skate-classics",
      ],
      color: "Multi-Color",
      designer: "Paul Van Doren",
      details: "Blue/Green-Yellow",
      gender: ["men"],
      grid_picture_url:
        "https://image.goat.com/375/attachments/product_template_pictures/images/011/051/956/original/335725_00.png.png",
      has_picture: true,
      has_stock: true,
      id: 4,
      keywords: [],
      main_picture_url:
        "https://image.goat.com/750/attachments/product_template_pictures/images/011/051/956/original/335725_00.png.png",
      midsole: "",
      name: "Old Skool 'Yacht Club'",
      nickname: "Yacht Club",
      original_picture_url:
        "https://image.goat.com/attachments/product_template_pictures/images/011/051/956/original/335725_00.png.png",
      product_template_id: 335725,
      release_date: null,
      release_date_unix: null,
      release_year: null,
      retail_price_cents: 6000,
      shoe_condition: "used",
      silhouette: "Old Skool",
      size_range: [
        10,
        10.5,
        11,
        11.5,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        3.5,
        4,
        4.5,
        5,
        5.5,
        6,
        6.5,
        7,
        7.5,
        8,
        8.5,
        9,
        9.5,
      ],
      sku: "VN0A38G1R1Q",
      slug: "old-skool-yacht-club-vn0a38g1r1q",
      status: "active",
      story_html:
        "<p>The Vans Old Skool ‘Yacht Club’ showcases bold color blocking inspired by traditional nautical flags. The shoe’s upper is executed with canvas quarter panels in kelly green, overlaid with a white leather side stripe, and contrasted by a blue suede toe cap and yellow suede heel panel. The multi-color design rests on a crisp white rubber midsole, accented with Vans’ signature ‘Off the Wall’ license plate in red.</p>\n",
      upper_material: "",
    },
    {
      title: "adidas",
      box_condition: "no_original_box",
      brand_name: "adidas",
      linkUrl: "shop/adidas",
      category: ["lifestyle"],
      collection_slugs: ["yeezy-1"],
      color: "Black",
      designer: "Kanye West",
      details: "Vanta/Vanta/Vanta",
      gender: ["men"],
      grid_picture_url:
        "https://image.goat.com/375/attachments/product_template_pictures/images/021/147/972/original/504187_00.png.png",
      has_picture: true,
      has_stock: true,
      id: 5,
      keywords: ["700", "Kanye West", "Yeezy"],
      main_picture_url:
        "https://image.goat.com/750/attachments/product_template_pictures/images/021/147/972/original/504187_00.png.png",
      midsole: "Boost",
      name: "Yeezy Boost 700 V2 'Vanta'",
      nickname: "Vanta",
      original_picture_url:
        "https://image.goat.com/attachments/product_template_pictures/images/021/147/972/original/504187_00.png.png",
      product_template_id: 504187,
      release_date: null,
      release_date_unix: null,
      release_year: null,
      retail_price_cents: 30000,
      shoe_condition: "new_no_defects",
      silhouette: "Yeezy Boost 700",
      size_range: [
        10,
        10.5,
        11,
        11.5,
        12,
        12.5,
        13,
        13.5,
        14,
        14.5,
        15,
        16,
        17,
        18,
        19,
        20,
        3,
        3.5,
        4,
        4.5,
        5,
        5.5,
        6,
        6.5,
        7,
        7.5,
        8,
        8.5,
        9,
        9.5,
      ],
      sku: "FU6684",
      slug: "yeezy-boost-700-v2-vanta-yzy-700-v2-vanta",
      status: "active",
      story_html: null,
      upper_material: "",
    },
  ],
};

const directoryReducer = (state= INITIAL_STATE,action) => {
    switch(action.type){
        default:
            return state;
    }
};

export default  directoryReducer;